hv_seg_class_consep:

  step_size: [80, 80]
  win_size: [270, 270]

  nr_types: 5 
  nuclei_types:
    Misc: 1
    Inflammatory: 2
    Epithelial: 3
    Spindle': 4

  input_norm: True
  remap_labels: False

hv_seg_class_pannuke:

  step_size: [164, 164]
  win_size: [256, 256]

  nr_types: 6 # View readme! background on GT is different
  nuclei_types: 
    Background: 0
    Neoplastic cells: 1
    Inflammatory: 2
    Connective/Soft tissue cells: 3
    Dead Cells: 4
    Epithelial: 5
    
  input_norm: True
  remap_labels: False